### ISSUE TITLE
Credit authors

### ISSUE THREAD

**Issue by nvh95** [webuild-community/advent-of-frontend#14]
Dear authors of Advent of Frontend 2022,

First, congratulations to all of us to make Advent of Frontend 2022 happen. We created 30 consecutive high-quality technical posts related to frontend development that give back to the community. Thank you guys so much. 🙏

I think it's also a good idea to credit all the authors by putting a hyperlink to their names after the posts. So, people might want to read more content produced by you. Eventually, it's the same purpose that spreads the knowledge to the community.

I can help with that. For example, this is how it should look like:
**Before**

1. [What's the HSL?](https://github.com/webuild-community/advent-of-frontend/blob/main/2022/day-01.md) - huytd

**After**

1. [What's the HSL?](https://github.com/webuild-community/advent-of-frontend/blob/main/2022/day-01.md) - [huytd](https://snacky.blog)

This is my idea:
- If you want to link your personal blog/ twitter/ linked in/ facebook/ link..., please comment your URL at this issue. For example:
```
@huytd commented
https://snacky.blog
```

- If you don't particularly choose a custom URL, we can fallback to use your GitHub profile.
- If you don't want to be mentioned, please let us know (via GitHub or Slack @nvh95)

Mention all awesome authors @huytd @ng-hai An @monodyle @ledongthuc @quannt @ZeroX-DG @kcjpop @thanhlmm @huyng12 Please let me know your favorite URL. Thanks.

**Comment by ZeroX-DG** [comment]
@ZeroX-DG commented
https://viethung.space/

**Comment by nvh95** [comment]
Thanks, @ZeroX-DG. You don't need the `@ZeroX-DG commented` anyway :joy:

**Comment by nvh95** [comment]
https://github.com/nvh95

**Comment by thanhlmm** [comment]
Awesome, please add my link as https://thanhle.blog/ 😇

**Comment by ZeroX-DG** [comment]
@nvh95 Well you didn't say that in the description. I'm just following your instructions 😂 Nah I'm just messing with you haha 😂

**Comment by monodyle** [comment]
🔥 mine
https://github.com/monodyle

**Comment by ledongthuc** [comment]
https://thuc.space/ 👍

**Comment by huytd** [comment]
I prefer using https://huy.rocks as snacky.blog is going to be retired soon.

**Comment by nvh95** [comment]
> snacky.blog is going to be retired soon.

@huytd Am I getting Deja Vu? I have a feeling this happened before 😌

**Comment by nvh95** [comment]
@quannt's blog: https://quannt.xyz/

**Comment by nvh95** [comment]
@kcjpop's blog: https://ehkoo.com/

**Comment by nvh95** [comment]
@ledongthuc's twitter: https://twitter.com/harriscode

**Comment by nvh95** [comment]
Updated all authors' url
